server:
  port: 11030
spring:
  application:
    name: electron-flights
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  config:
    import:
      - nacos:${spring.application.name}.yml?group=${spring.profiles.active}&refreshEnable=true
---
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000/electron
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/electron_flights_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Hj1234
    hikari:
      connection-test-query: "SELECT 1"
  data:
    redis:
      host: 192.168.2.2
      port: 6379
      database: 6
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  cloud:
    nacos:
      username: root
      password: 1234
      config:
        server-addr: 192.168.2.2:8848
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: ${spring.profiles.active}
mybatis-plus:
  configuration:
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
spring:
  config:
    activate:
      on-profile: prod