/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../src/components/layout/Aside.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./../src/components/layout/Header.vue')['default']
    IMdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    IMdiAlignHorizontalLeft: typeof import('~icons/mdi/align-horizontal-left')['default']
    IMdiAlignHorizontalRight: typeof import('~icons/mdi/align-horizontal-right')['default']
    IMdiLogoutVariant: typeof import('~icons/mdi/logout-variant')['default']
    IMdiMoonAndStars: typeof import('~icons/mdi/moon-and-stars')['default']
    IMdiPasswordReset: typeof import('~icons/mdi/password-reset')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const Aside: typeof import('./../src/components/layout/Aside.vue')['default']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const Header: typeof import('./../src/components/layout/Header.vue')['default']
  const IMdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
  const IMdiAlignHorizontalLeft: typeof import('~icons/mdi/align-horizontal-left')['default']
  const IMdiAlignHorizontalRight: typeof import('~icons/mdi/align-horizontal-right')['default']
  const IMdiLogoutVariant: typeof import('~icons/mdi/logout-variant')['default']
  const IMdiMoonAndStars: typeof import('~icons/mdi/moon-and-stars')['default']
  const IMdiPasswordReset: typeof import('~icons/mdi/password-reset')['default']
  const IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}